### ISSUE TITLE
Refreshing for data while having data shows "failed to retrieve new data"

### ISSUE THREAD

**Issue by Skk-tj** [Skk-tj/HoloCal#1]

**Comment by Ricky-227** [comment]
I was about to ask about data refreshing, looks like you are working on it

**Comment by Skk-tj** [comment]
> I was about to ask about data refreshing, looks like you are working on it

What's the issue? (I kinda still need to know in case it's something different on my end)

**Comment by Ricky-227** [comment]
It looks fine right now, I was wondering if there is going to be a pull to refresh function added later

**Comment by Skk-tj** [comment]
> It looks fine right now, I was wondering if there is going to be a pull to refresh function added later

Unfortunately due to limitations (or bugs) in SwiftUI pull-to-refresh is only available on iPhones. You can always tap the sidebar buttons to refresh.
