### ISSUE TITLE
Big widget that shows ~4 current/upcoming streams

### ISSUE THREAD

**Issue by Skk-tj** [Skk-tj/HoloCal#35]

**Comment by 3zk-4112** [comment]
I can't comprehend the difficulty of app development. but I hope these widgets will be implemented soon.

**Comment by Skk-tj** [comment]
> I can't comprehend the difficulty of app development. but I hope these widgets will be implemented soon.

Thanks for voicing your support of this feature. This will be a new feature in our next release.
