### ISSUE TITLE
The combination of thumbnails and titles is strange in multiple widgets.

### ISSUE THREAD

**Issue by 3zk-4112** [Skk-tj/HoloCal#52]
I am Japanese. I am not good at English. It may be funny because I use Google Translate

Thank you for responding to my request to support Nori Pro and Nanashi inc. the other day.

Today I will report ‘multiple live’ and ‘multiple upcoming’ or ‘multiple past’ widget bug.
These widgets display 2 thumbnails(A,B) and 2 titles(a,b). but the combination doesn't match!

True↓
 A B
 a b

Now↓
 A B
 b a

Thanks for the great app. Hope it gets better. good luck

**Comment by Skk-tj** [comment]
バグリポートありがとうございます。今後も日本語でバグリポートを提出してもいいですが、今回英語でバグリポートをしてありがとうございます！

Thank you for the bug report. Feel free to report any bugs in Japanese in the future. I understand a bit Japanese :) 

I noticed this weird bug a few times. Not sure how to fix it yet but I'll keep an eye on it.
